### ISSUE TITLE
Unrecognized function or variable 'TensProd_GL'

### ISSUE THREAD

**Issue by turovapolina** [lockEF/SupCP#1]
Dear colleagues,

I am trying to use your code for supervised PARAFAC and unfortunately, I received a mistake:
![image](https://user-images.githubusercontent.com/61549119/78382870-2b6e6280-75e0-11ea-85bc-cc12e0c3f69b.png)
I didn't find any modules with this function or any other examples with it. Could you please clarify how can I define this function?

Best regards,
Polina

**Comment by lockEF** [comment]
Thank you for notifying us.  The 'TensProd_GL' function is outdated and should be replaced with just 'TensProd'.  We have made this change to the code in the current version.  Please let us know if you encounter any other issues.

**Comment by turovapolina** [comment]
> Thank you for notifying us. The 'TensProd_GL' function is outdated and should be replaced with just 'TensProd'. We have made this change to the code in the current version. Please let us know if you encounter any other issues.

Dear @lockEF,

Thank you for your answer!
I am sorry to disturb you once again. I tried to perform SupParafacEM with same arrays X and Y as in your example with aminoacids but one more problem appeared:
![image](https://user-images.githubusercontent.com/61549119/78500943-1de0e600-7762-11ea-80b0-1bb9f010c8c8.png)
 
After thatI tried to perform  line by line the same algorythm as in your Example.m script but I received the same mistake:
![image](https://user-images.githubusercontent.com/61549119/78500983-57195600-7762-11ea-83a9-54d61f50092a.png)

Do you have any suggestions why TensProd function doesn't work?
As far as I understand it refers to khatri-rao function kr.m and it requires two arguments but we give only one (tempL).

Thank you very much in advance!

**Comment by lockEF** [comment]
Thanks again for the comment.  It seems that multiple versions of the kr.m function have been developed.  I have uploaded the version used in our function as an additional file.   Please let me know if you encounter any more issues.

**Comment by turovapolina** [comment]
Dear @lockEF,

Thank you very much! Now it works!
But another strange thing happened: 
I decomposed my own data using supervised PARAFAC and it gives me the same loadings as usual PARAFAC.
At the first time I thought that this happened because my samples are already resolved in unsupervised model and supervised technique doesn't give me any advantages. But then I tried to apply SupPARAFACem to the dataset where scores from PARAFAC are not satisfying at all and received the same result! I am just wondering how it works with your examples? Do you receive different loadings? Or probably I misunderstand the idea of supervised PARAFAC at all.
Thank you very much in advance!

Best regards,
Polina

**Comment by lockEF** [comment]
The results for SupCP can be similar to those of regular PARAFAC under certain settings, especially if the low-rank signal for the tensor (X) is strong and its relation to the response (Y) is weak.  Situations in which the low-rank signal (X) is relatively weak but its relation to the responses (Y) is strong will have the most improvement with a supervised approach.  See the simulations in https://arxiv.org/pdf/1609.03228.pdf for more detail.
